-- Idempotent fixes for services table
-- rename name -> service_name if needed
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='name') > 0
 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='service_name') = 0,
 'ALTER TABLE services CHANGE COLUMN name service_name VARCHAR(150) NOT NULL',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- add price column if missing but unit_price exists
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='price') = 0
 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='unit_price') > 0,
 'ALTER TABLE services ADD COLUMN price DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER description',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- copy values from unit_price
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='price') > 0
 AND (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='unit_price') > 0,
 'UPDATE services SET price = unit_price WHERE (price IS NULL OR price=0)',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- add period column
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='period') = 0,
 "ALTER TABLE services ADD COLUMN period ENUM('ay','yil') NOT NULL DEFAULT 'ay'",
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- add firm_id
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='firm_id') = 0,
 'ALTER TABLE services ADD COLUMN firm_id INT UNSIGNED NULL',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- populate firm_id if null
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='firm_id') > 0,
 'UPDATE services SET firm_id=(SELECT MIN(id) FROM firms) WHERE firm_id IS NULL',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- make firm_id not null
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND COLUMN_NAME='firm_id' AND IS_NULLABLE='YES') > 0,
 'ALTER TABLE services MODIFY firm_id INT UNSIGNED NOT NULL',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- add foreign key
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND CONSTRAINT_NAME='fk_service_firm') = 0,
 'ALTER TABLE services ADD CONSTRAINT fk_service_firm FOREIGN KEY (firm_id) REFERENCES firms(id) ON DELETE CASCADE',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- unique index on service_name
SET @stmt := NULL;
SELECT IF(
 (SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='services' AND INDEX_NAME='service_name') = 0,
 'ALTER TABLE services ADD UNIQUE KEY service_name (service_name)',
 'SELECT 1') INTO @stmt;
PREPARE stmt FROM @stmt; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ensure charset
ALTER TABLE services CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
